using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using Dapper;
using FluentAssertions;
using FluentAssertions.Execution;
using Infastructure;
using Newtonsoft.Json;

namespace test;

[TestFixture]
public class FriendTest
{
    private string resetbd = $@"
DROP SCHEMA IF EXISTS keepsocial CASCADE;
CREATE SCHEMA keepsocial;

create table if not exists keepsocial.users (
    id integer generated by default as identity,
    name VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    profileDescription VARCHAR(500),
    birthday DATE,
    avatarUrl VARCHAR,
    isDeleted boolean NOT NULL,
    constraint userpk
        primary key (id)
);


create table if not exists keepsocial.password_hash (
    user_id integer,
    hash VARCHAR(350) NOT NULL ,
    salt VARCHAR(180) NOT NULL ,
    algorithm VARCHAR(12) NOT NULL ,
    FOREIGN KEY(user_id) REFERENCES keepsocial.users(id)
);

create table if not exists keepsocial.chatrooms (
    rom_id integer generated by default as identity,
    rom_name VARCHAR,

    primary key (rom_id)
);

create table if not exists keepsocial.posts
(
    id integer generated by default as identity,
    author_id integer not null ,
    text VARCHAR(500) not null ,
    img_url VARCHAR,
    created timestamp not null,
    constraint postpk
        primary key (id),
    foreign key(author_id) references keepsocial.users(id)
);

create table if not exists keepsocial.chatroom_users_relation (
    rom_id integer ,
    user_id integer,

    FOREIGN KEY(rom_id) REFERENCES keepsocial.chatrooms(rom_id),
    FOREIGN KEY(user_id) REFERENCES keepsocial.users(id)
);

create table if not exists keepsocial.messages (
    id integer generated by default as identity,
    rom_id integer,
    user_id integer,
    message VARCHAR,
    time_Send timestamp,

    CONSTRAINT message_pk primary key (id),
    FOREIGN KEY(rom_id) REFERENCES keepsocial.chatrooms(rom_id),
    FOREIGN KEY(user_id) REFERENCES keepsocial.users(id)
);
create table if not exists keepsocial.friend_relation
(
    user1_id integer,
    user2_id integer,

    CONSTRAINT PK_friends PRIMARY KEY (user1_id, user2_id),
    FOREIGN KEY (user1_id) REFERENCES keepsocial.users (id),
    FOREIGN KEY (user2_id) REFERENCES keepsocial.users (id)
);

create table if not exists keepsocial.friend_request_table
(
    request_id integer generated by default as identity,
    requester integer,
    requested integer,
    response bool,

    CONSTRAINT PK_friendRequest PRIMARY KEY (request_id),
    FOREIGN KEY (requester) REFERENCES keepsocial.users (id),
    FOREIGN KEY (requested) REFERENCES keepsocial.users (id)
);

create table if not exists keepsocial.validation_numbers
(
  user_id integer NOT NULL,
  validation_number integer NOT NULL,
  created timestamp not null,
  FOREIGN KEY (user_id) REFERENCES keepsocial.users(id)
);

create table if not exists keepsocial.comments
(
   id integer generated by default as identity,
   post_id integer not null,
   author_id integer not null,
   text VARCHAR(500) not null,
   img_url varchar,
   created timestamp not null,
   primary key (id),
   foreign key(post_id) references keepsocial.posts(id),
   foreign key (author_id) references keepsocial.users(id)
);

create table if not exists keepsocial.follow_relation
(
    followed_id INT NOT NULL,
    follower_id INT NOT NULL,
    CONSTRAINT PK_follow PRIMARY KEY (followed_id, follower_id),
    FOREIGN KEY (followed_id) REFERENCES keepsocial.users(id),
    FOREIGN KEY (follower_id) REFERENCES keepsocial.users(id)
);

insert into keepsocial.users(id,name,email,birthday,isdeleted) values (111,'test tester','test@email.com',date('2023-02-24'),false);
insert into keepsocial.users(id,name,email,birthday,isdeleted) values (112,'test','secondtestUser@email.com',date('2023-02-10'),false);

insert into keepsocial.password_hash(user_id,hash,salt,algorithm) values (111,'yfY6Hw8jaQO6HDGwCcC2RmO4QnjWRUMvL2BGJffBgy/51a1QH5grtXBCY4erDFV/Tpf5kFkkhrM7wAmLrMy8x2lHojaVTrt0T9sFKwZu3FvKW1WViCylor+4UeyX6aAUEbnBzFoUegQbf1IqC5cfbnmyT5Fb6u1YxB6uE6y1m/X/15VbwLpYH3TSVgr2p7rKC+HzCMechi7MdABZml9QrYEzgn21ViA0wuEk8vxCwxjdU9cAJQiGzNt0VBQ0Sh9CNGbsDndegX/IzQYZlwjYVbeFbyTaVEEB6u2w+5Gtpdg++tQQx1wlBZTnRxMB1NVhqAKsgKhWkD58NYTA+VoV1Q==','npTtNPhSUDkDDEoRqNF+fNG/ZLyayMkBSpdhQuXP72QGkSWBKzm3MuVmz9oxSfjCLcTYB8AfyjcgUGVVrPfOxcnV3jCRWq5DeEVsm3L7JkI5rkEY30OlcomaT7VDMlu0N+S96g3lYfesG80NZQS/xaO2Qq/B8F1tb8na4nT840M=','argon2id');
insert into keepsocial.password_hash(user_id,hash,salt,algorithm) values (112,'WWnDFi0C+RSi94i08E446PldkD07IdE6X0L1vwF+pPH6gZ+2GHTEzcbx0VRcgrdiSMWZuDGv6rvepcbYLgs7ChjE4Je86dAn2ec13nY2xqdtFb0EzY/HWOvXukBMAjgZrQJJxXYbWsax/q8Xsbwt/65EsTmuhoAtXZBTaGzyJ7OO8Qr50dlfeUw0WnqMYVNfM0JMRJsbYF+8jAYLdOxr4G+czIq2nrjqNVdWmtYOlkUWkORWwQCGnQJoJkbElvHdENVACbpqMT2+8DzEfMz0YTMd9KSqRh4w9oBm8Fp54lPAziwLOXPeUA5OULVR7rJbaRX/PHZwB5KPrVXcdM+PAQ==','UdzXfqmbj/yDWVPLSkAX4J668TZ07iG4BE8DQIe6zdOo3UgPz8nkq7FEIkwB48Etmh56tqIMaQCBvejXO10IFHjMUnYj5vyGwcFMyqo1xmnqddmzVDGp1QuvpxBwyUOCT3dkGUcoGzdmgZwXFCfB83APEXNe7pux2U/lhujMHV4=','argon2id');
";

    private string apirUrl = "";
    private HttpClient _httpClient;

    [SetUp]
    public void Setup()
    {
        _httpClient = new HttpClient();
        _httpClient.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", Environment.GetEnvironmentVariable("testToken"));
        apirUrl = "http://localhost:5000/api/";
    }

    public class RequestUpdateDto
    {
        public required int RequesterId { get; set; }

        public required int RequestId { get; set; }

        public required bool Response { get; set; }
    }

    [Test]
    public async Task AcceptRequest()
    {
        string apicall = apirUrl + "account/FriendRequestsResponse";
        Helper.TriggerRebuild(resetbd);

        var sqlSetFriendrequest =
            $@"INSERT INTO keepsocial.friend_request_table(request_id, requester, requested) VALUES (101, 112, 111);";
        using (var conn = Helper.DataSource.OpenConnection())
        {
            conn.Query(sqlSetFriendrequest);
        }

        var body = new RequestUpdateDto()
        {
            RequesterId = 112,
            RequestId = 101,
            Response = true
        };

        HttpResponseMessage responseMessage;
        try
        {
            responseMessage = await _httpClient.PutAsJsonAsync(apicall, body);
            TestContext.WriteLine("full body response: " + await responseMessage.Content.ReadAsStringAsync());
        }
        catch (Exception e)
        {
            throw new Exception("Failed to create resposne to request", e);
        }

        var sql = @$"SELECT count(user1_id) from keepsocial.friend_relation 
            where (user1_id = 111 and user2_id = 112) 
        OR (user1_id = 112 and user2_id = 111);";
        
        var sql2 = @$"SELECT count(*) from keepsocial.friend_request_table 
            WHERE requested = 111 and requester = 112";

        bool isFriends = false;
        bool requestexist = false;
        using (var conn = Helper.DataSource.OpenConnection())
        {
            isFriends = conn.ExecuteScalar<int>(sql) >= 1;
            requestexist = conn.ExecuteScalar<int>(sql2) >= 1;
        }

        using (new AssertionScope())
        {
            responseMessage.StatusCode.Should().Be(HttpStatusCode.OK);

            isFriends.Should().Be(true);
            requestexist.Should().Be(false);
        }
    }

    [Test]
    public async Task DeclineRequest()
    {
        string apicall = apirUrl + "account/FriendRequestsResponse";
        Helper.TriggerRebuild(resetbd);

        var sqlSetFriendrequest =
            $@"INSERT INTO keepsocial.friend_request_table(request_id, requester, requested) VALUES (101, 112, 111);";
        using (var conn = Helper.DataSource.OpenConnection())
        {
            conn.Query(sqlSetFriendrequest);
        }

        var body = new RequestUpdateDto()
        {
            RequesterId = 112,
            RequestId = 101,
            Response = false
        };

        HttpResponseMessage responseMessage;
        try
        {
            responseMessage = await _httpClient.PutAsJsonAsync(apicall, body);
            TestContext.WriteLine("full body response: " + await responseMessage.Content.ReadAsStringAsync());
        }
        catch (Exception e)
        {
            throw new Exception("Failed to create resposne to request", e);
        }

        var sql = $@"select request_id as {nameof(RequestUpdateDto.RequestId)},
       requester as {nameof(RequestUpdateDto.RequesterId)},
       response as {nameof(RequestUpdateDto.Response)}
        from keepsocial.friend_request_table where requested = 111";

        RequestUpdateDto Checkrequestanwser = null;
        using (var conn = Helper.DataSource.OpenConnection())
        {
            Checkrequestanwser = conn.QuerySingle<RequestUpdateDto>(sql);
        }

        using (new AssertionScope())
        {
            responseMessage.StatusCode.Should().Be(HttpStatusCode.OK);

            body.RequesterId.Should().Be(Checkrequestanwser.RequesterId);
            body.RequestId.Should().Be(Checkrequestanwser.RequestId);
            body.Response.Should().Be(Checkrequestanwser.Response);
        }
    }

    [Test]
    public async Task SendRequest()
    {
        string apicall = apirUrl + "account/SendFriendRequest112";
        Helper.TriggerRebuild(resetbd);
        
        HttpResponseMessage responseMessage;
        try
        {
            responseMessage = await _httpClient.PostAsJsonAsync(apicall,"");
            TestContext.WriteLine("full body response: " + await responseMessage.Content.ReadAsStringAsync());
        }
        catch (Exception e)
        {
            throw new Exception("Failed to create resposne to request", e);
        }
        
        FriendRequestResponse response;

        try
        {
            response = JsonConvert.DeserializeObject<FriendRequestResponse>(await responseMessage.Content.ReadAsStringAsync()) ??
                       throw new InvalidOperationException();
        }
        catch (Exception e)
        {
            throw new Exception(Helper.BadResponseBody("bad response"), e);
        }
        
        var sql = @$"select request_id from keepsocial.friend_request_table where requester = 111 AND requested = 112;";

        int requestId = -117; // Yes this is a halo reference 
        
        using (var conn = Helper.DataSource.OpenConnection())
        {
            requestId = conn.QuerySingle<int>(sql);
        }
        
        using (new AssertionScope())
        {
            responseMessage.StatusCode.Should().Be(HttpStatusCode.OK);
            response.responseMessage.Should().Be("request have been created");
            response.requestId.Should().Be(requestId);
        }
    }

    [Test]
    public async Task RemoveFriend()
    {
        string apicall = apirUrl + "account/RemoveFriend112";
        Helper.TriggerRebuild(resetbd);

        var sqlSetFriend = $@"INSERT INTO keepsocial.friend_relation(user1_id, user2_id) VALUES (111, 112);";

        using (var conn = Helper.DataSource.OpenConnection())
        {
            conn.Query(sqlSetFriend);
        }
        
        HttpResponseMessage responseMessage;
        try
        {
            responseMessage = await _httpClient.DeleteAsync(apicall);
            TestContext.WriteLine("full body response: " + await responseMessage.Content.ReadAsStringAsync());
        }
        catch (Exception e)
        {
            throw new Exception("Failed to dellete friend", e);
        }

        var sqlCheck = @$"SELECT COUNT(*) FROM keepsocial.friend_relation WHERE (user1_id = 111 and user2_id = 112);";
        var dbcheck = Helper.checkifexists(sqlCheck);

        using (new AssertionScope())
        {
            responseMessage.StatusCode.Should().Be(HttpStatusCode.OK);
            dbcheck.Should().Be(0);
        }

    }
}