using Npgsql;

namespace test;

public class Logintest
{
    private string apirUrl = "";
    private HttpClient _httpClient;
    private  readonly NpgsqlDataSource _dataSource;

    private string resetbd = $@"SELECT * FROM keepsocial.users;

drop table if exists keepsocial.messages;
drop table if exists keepsocial.chatroomUsersRealation;
drop table if exists keepsocial.chatrooms;

create table if not exists keepsocial.chatrooms (
    rom_id integer generated by default as identity,
    rom_name VARCHAR,

    primary key (rom_id)
);

create table if not exists keepsocial.chatroomUsersRealation (
    rom_id integer ,
    user_id integer,

    FOREIGN KEY(rom_id) REFERENCES keepsocial.chatrooms(rom_id),
    FOREIGN KEY(user_id) REFERENCES keepsocial.users(id)
);

create table if not exists keepsocial.messages (
    rom_id integer,
    user_id integer,
    message VARCHAR,

    FOREIGN KEY(rom_id) REFERENCES keepsocial.chatrooms(rom_id),
    FOREIGN KEY(user_id) REFERENCES keepsocial.users(id)
);
insert into keepsocial.users(id,name,email,birthday,isdeleted) values (111,'test tester',2023-02-24,false);
insert into keepsocial.users(id,name,email,birthday,isdeleted) values (112,'test',2023-02-10,true);
insert into keepsocial.password(user_id,hash,salt) values (111,'6Po8CEcjkfC5Scoze2n5WoI7yLFePCZlEmQNPY9M0UFP0ghMegnM2t3k8HpcE/EkdYxOPJDj1XBM9J47eOdON6N9thahuXvlbY3D8Ag/y1JgHNw2ea6E5l1VWVSz7kCrQudnazfVTMQuce4emRjSLSAZAaoF55zXmBYjFOqZ5xX13TV5/UJUPkKf7uRKGNyTf1o/LlnZqmMsziF6unmCZTBgpn3W1oHr3zSh2Xm7dohmVN8+eDXPchVhUTha4u7QG75EFsILQfgALPDt3N/DUX/pHKBTVGcMAQWX1zAKyXdNPsp3MtiioBFnsJ+Zpn37mTRWNAPUMojvFekGGvb9zQ==','WwoEFhsDKJMTyb4GzbfV8inzImVI404JZSeQXWoptlUaZmuoTrKq5b/5WIqIXpeDuny7WbgDf3Hi3SuK1EmPNqTxGNbSJk3bPxufdhxwlaPXHa4vPOajEqdtLDqD+WpjvF5QK/oSTS/XB8Rj0oY0BOqW/k+KBiMTjyNc2fjJEpQ=')
insert into keepsocial.password(user_id,hash,salt) values (112,'vozhha9O1+FMJbqhl2SU4AMYCQyThZkWWpGUkZiPfjcFvccaGhTjhAQniWiy3X2n+hXxHj7HyEp6bj2I9qWxUyTMce+zxECoP4Z34NH7H+R2pWm8xoeL0XxyvmlIFwx5hXDd+UT1JRS19Tm8m3YTYJNAjaYS3/nDB1jsLBP6JUVHHxjupKOyEiWn3E/lPb30DD6UVL7XgOURhDxXinakVuL/OYfvyun0KjkH0X3BBTz4nVxp9amighDetwNOMqbN5pHIDVlypkubzmA+a4gTaz3n/OddndT1LIaybkK/xMpjCJ2LoETkGI4DKRrGT3OZVLZXsVs5qWTXRq5llqp7Mg==','IJUp5fhQdakTW1CytDOCajKBQsy1BrDN4568vqne6OwJMS/O6u3rDFBwl/IRaYWRgmTep560x5lPZXJ4ZjHrxg98NBjD4J7skTG6Jxi+1kQnAs6uFvl7QmXdWePzZnMDSJFbmyXfM628pFhrDFF3hbhE+/ZJCbc0UbrXlrlCgn4=')
";

    public Logintest(NpgsqlDataSource dataSource)
    {
        _dataSource = dataSource;
    }

    [SetUp]
    public void Setup()
    {
        _httpClient = new HttpClient();
        apirUrl = "http://localhost:5000/";
    }

    [Test]
    public async Task login()
    {
        
    }
}