# This is a basic workflow to help you get started with Actions


name: YAML for testing on git

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #Set up dotnet with version 8 for /API tests 
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
      #Runs the api and the test, once finished it wil terminate the api so the proces can finish

      - run: cd test && dotnet build
      - name: Run the APITest
        run: cd API && dotnet build && dotnet run & (sleep 60 && cd test && dotnet test && kill -9 $(lsof -t -i:5000))
        env:
          pgconn: ${{secrets.pgconn}}
